<?php

namespace Skear\ApplicationBundle\Repository;

/**
 * DriveFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriveFileRepository extends \Doctrine\ORM\EntityRepository
{
}
