<?php

namespace Skear\ApplicationBundle\Repository;

/**
 * DriveCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriveCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
