categorie_index:
    path:     /
    defaults: { _controller: "SkearApplicationBundle:DriveCategorie:index" }
    methods:  GET

categorie_show:
    path:     /{id}/show
    defaults: { _controller: "SkearApplicationBundle:DriveCategorie:show" }
    methods:  GET

categorie_new:
    path:     /new
    defaults: { _controller: "SkearApplicationBundle:DriveCategorie:new" }
    methods:  [GET, POST]

categorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "SkearApplicationBundle:DriveCategorie:edit" }
    methods:  [GET, POST]

categorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "SkearApplicationBundle:DriveCategorie:delete" }
    methods:  DELETE
