#skear_user:
#    resource: "@SkearUserBundle/Resources/config/routing.yml"
#    prefix:   /users

skear_application:
    resource: "@SkearApplicationBundle/Resources/config/routing.yml"
    prefix:   /drive

#fos_user:
#   resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"